spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false  # OSIV 해제
    hibernate:
      ddl-auto: validate   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true

file:
  profileDir: /Users/dragonwaterr/Desktop/week4/src/main/resources/static/images/profile/
  postDir: /Users/dragonwaterr/Desktop/week4/src/main/resources/static/images/post/



logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off

