spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    open-in-view: false  # OSIV 해제
    hibernate:
      ddl-auto: validate   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 10MB

file:
  profileDir: /Users/dragonwaterr/Desktop/week4/src/main/resources/static/assets/images/profile/
  postDir: /Users/dragonwaterr/Desktop/week4/src/main/resources/static/assets/images/post/



logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off

